export const eightBall: string[] = [
  'sounds like something that might happen',
  'you kiddin? not in a million years!',
  'yikes, try asking someone else maybe',
  "the answer to that is spicy, too bad I'm sworn to secrecy",
  'oh absolutely',
  'oh hell no',
  'I sure hope not',
  "I'd bet money on it",
  'no clue!',
  'hell if I know',
  'eh, try asking Kikai',
  "I'd love to tell you, but I think Chrissy might exorcise me from the server",
  "wouldn't you like to know?",
  'with a ton of luck, maybe',
  'naaaah',
  "you're asking the wrong spirit",
];
